version: 2.1
executors:
  node8:
    docker:
    - image: circleci/node:8-jessie
      environment:
        NPM_CONFIG_PREFIX: "~/.npm-global"
    working_directory: ~/repo

commands:
  setup:
    steps:
    - checkout
    - restore_cache:
        keys:
        - v2-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
    - run:
        name: install npm 6.10.0
        command: sudo npm -g install npm@6.10.0
    - run:
        name: Installing Dependencies
        command: npm install
    - save_cache:
        paths:
        - node_modules
        key: v2-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
    - run:
        name: prepare test git user
        command: git config --global user.email "circleci@example.com" && git config --global user.name "CircleCi Build"

orbs:
    helix-smoke-tests: adobe/helix-smoke-tests@0.0.10
    win: circleci/windows-tools@0.1.0

jobs:
  build_win:
    parallelism: 1
    executor: win/preview-default
    steps:
      - run: git config --global core.autocrlf false
      - run:
          name: prepare test git user
          command: git config --global user.email "you@example.com"
      - run:
          name: prepare test git user
          command: git config --global user.name "Your Name"
      - checkout
      - run: choco install nodejs --version 8.16.0
      - run: npm install
      - run: mkdir junit

      # test & get code coverage
      - run:
          name: Running Tests
          command: ./node_modules/.bin/mocha --timeout 10000 --reporter xunit test --reporter-options output=junit/test.xml
          environment:
            MOCHA_FILE: junit/test-results.xml
          when: always

      - store_test_results:
          path: junit

      - store_artifacts:
          path: junit  

  build:
    executor: node8

    steps:
    - setup
        # run tests!
    - run: mkdir junit
    - run:
        name: prepare test git user
        command: git config --global user.email "you@example.com" && git config --global user.name "Your Name"

    # test & get code coverage
    - run:
        name: Test and Code Coverage
        command: npm run test-ci
        environment:
          MOCHA_FILE: junit/test-results.xml

    - store_test_results:
        path: junit

    - store_artifacts:
        path: junit

  publish-pre-release:
    executor: node8

    steps:
    - setup
    - add_ssh_keys:
        fingerprints:
          - "c3:cc:4e:ec:21:9b:64:b5:61:fb:ba:61:62:cf:62:96"
    - run:
        name: revert changes to package-lock.json
        command: git checkout -- package-lock.json

    - run:
        name: configure npm registry
        command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

    - run:
        name: Semantic Release
        command: npm run semantic-release

workflows:
  version: 2
  build:
    jobs:
    # publish pre-releases on master
    - publish-pre-release:
        requires:
        - build
        - build_win
        filters:
          branches:
            only: master
    - build
    - build_win
  smoke:
    jobs:
        - helix-smoke-tests/run:
            remote_repo: adobe/helix-continuous
